# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev --deploy

      - save_cache:
          paths:
            - ".venv"
          key: v1-dependencies-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            pipenv run pytest

  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev --deploy
      - run:
          name: Set deploy branch
          command: |
            echo 'export DEPLOY_BRANCH=`[[ $CIRCLE_BRANCH = "master" ]] && echo "production" || echo $CIRLCE_BRANCH`' >> $BASH_ENV
      - run:
          name: Print DEPLOY_BRANCH
          command: |
            echo $DEPLOY_BRANCH
      - run:
          name: Deploy via Zappa
          command: |
            pipenv run zappa deploy $DEPLOY_BRANCH || pipenv run zappa update $DEPLOY_BRANCH

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
